### ISSUE TITLE
environments cookbook_versions must have a version specifier

### ISSUE THREAD

**Issue by bencaron** [mdxp/knife-backup#10]
I got this error while restoring my backup from a Chef10 install to a Chef11:

```
ERROR: The data in your request was invalid
Response: Invalid value '0.5.0' for cookbook_versions
```

I found that my cookbooks versions constraints where not "hard" enough when I did not accept variations (like ~>, >=, etc.) and that I've specified an exact version (like "0.5.0").

I suppose this is a change in Chef 11.

I don't know if this would be correct to filter this kind of constraints in the backup and/or restore tho. 

I've fixed my enviroments JSON dumps by filtering them with this small script:

```ruby
require 'json'

# fake Chef::Environment class for JSON parse
class Chef
  class Environment
  end
end

ARGV.each do |zejsonfile|
  jsonout = ""
  File.open(zejsonfile, 'r') do |zefile|
    parsed = JSON.parse(zefile.read)
    if parsed.include? 'cookbook_versions'
      parsed['cookbook_versions'].each do |cookbook, version|
        if version =~ /^\d/
          parsed['cookbook_versions'][cookbook] = "= #{version}"
        end
      end
      jsonout = JSON.dump parsed
    end
  end
  unless jsonout == ""
    File.open(zejsonfile, 'w') do |zefile|
      zefile.write jsonout
    end
  end
end
```

**Comment by pmoosh** [comment]
Thank you @bencaron @keivnhuang @nshenry03 - closing this since no changes are required for knife-backup
