### ISSUE TITLE
cookbooks not being backed up? 

### ISSUE THREAD

**Issue by bimp** [mdxp/knife-backup#21]
running the latest 0.0.8 version and when executing "knife backup export", nodes/environments/databags/roles gets backed up but cookbooks don't get backed up. 

when I try to execute "knife backup export cookbooks", the same results happen.

**Comment by dandunckelman** [comment]
I recently experienced this as well.  Enabling `verbose` mode revealed the following error:

    $ knife backup export cookbooks -V
    INFO: Using configuration from /home/ddunckel/.chef/knife.rb
    Backing up cookbooks
    Backing up cookbook ulimit
    Downloading ulimit cookbook version 0.3.2
    Downloading resources
    ERROR: SSL Validation failure connecting to host: HOSTNAME - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

To solve this, I added `ssl_verify_mode :verify_none` to my `knife.rb` until I could setup the trusted certs.

**Comment by pmoosh** [comment]
Closing - no action needed
