### ISSUE TITLE
Component backup fails if a single item cannot be accessed

### ISSUE THREAD

**Issue by tas50** [mdxp/knife-backup#23]
When backing up from Hosted chef if a single item has permissions that prevent you from reading the object the entire component backup fails.

Example with users:

ERROR: You authenticated successfully to https://api.opscode.com/organizations/org as your_username but you are not authorized for this action
Response:  You are not authorized to view user user_with_bad_perms

**Comment by pmoosh** [comment]
@jamescarniglia @tas50
fixed with
https://github.com/mdxp/knife-backup/commit/862327716d8af831a92069873f6d5cc88679e81e

Still need to update the README.md
