### ISSUE TITLE
Getting error on backing up the chef server using knife

### ISSUE THREAD

**Issue by tarungarg** [mdxp/knife-backup#26]
This is on Ubuntu machine.
1. I installed gem on chef server for backup the server.
        
        sudo gem install knife-backup

2. Now I create a knife.rb file the following configuration.

	  log_level                           :info
	  log_location                      STDOUT
	  validation_client_name     'chef-validator'
	  validation_key                   '/etc/chef-server/chef-validator.pem'
	  chef_server_url                 'https://server_ip'

3. When I run the following command,

        sudo knife backup export -D /etc/chef/backups -c knife.rb

it is showing me error:-

/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-7.0.4/lib/ohai/loader.rb:188: warning: character class has `[' without escape
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-7.0.4/lib/ohai/loader.rb:188: warning: regexp has `]' without escape
Backing up clients
ERROR: Your private key could not be loaded from /etc/chef/client.pem
Check your configuration file and ensure that your private key is readable

**Comment by pmoosh** [comment]
Closing this a configuration issue.

thanks @tyrken
