### ISSUE TITLE
export from chef 10.24 fails

### ISSUE THREAD

**Issue by qhartman** [mdxp/knife-backup#34]
I get to backing up users and then:

ERROR: JSON::ParserError: Unsupported `json_class` type 'Chef::WebUIUser'

My  knife install is 11.x via omnibus, and I had to have gem be conservative to get chef-backup installed
looking into collecting more debug info now....

**Comment by pmoosh** [comment]
@qhartman did you tried and encounter this issue with the latest knife version?
If so just reopen the issue again

**Comment by qhartman** [comment]
I no longer have a 10.24 install to test against, we've finally joined the modern world. Sorry!
