### ISSUE TITLE
Misleading error when restoring cookbooks

### ISSUE THREAD

**Issue by xmik** [mdxp/knife-backup#35]
When restoring cookbooks using the following command:
````bash 
admin@host:~$ ls -l /home/admin/backup_chef_server/cookbooks/
drwxr-xr-x 5 user2 user2 4096 Feb 25 17:15 apt-2.6.1
drwxr-xr-x 5 user2 user2 4096 Feb 25 17:15 dummy_cookbook-0.1.0
drwxr-xr-x 5 user2 user2 4096 Feb 25 17:15 dummy_cookbook-0.2.0
admin@host:~$ knife backup restore cookbooks roles environments clients users nodes -D /home/admin/backup_chef_server
/ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
WARNING: This will overwrite existing data!
Do you want to restore backup, possibly overwriting exisitng data? (Y/N)y
=== Restoring cookbooks ===
ERROR: Errno::ENOENT: No such file or directory - /home/admin/backup_chef_server/cookbooks/dummy_cookbook
````

The reason is that the method responsible for restoring cookbooks creates a symlink from e.g. dummy_cookbook-0.1.0/ to dummy_cookbook/ and the symlink cannot be created if there are too restrictive permissions set. 

It would be helpful to get an error about invalid permissions instead of not existing directory.

**Comment by ruicovelo** [comment]
And I guess this will not work at all on Windows machines.

**Comment by xmik** [comment]
I have never used it on Windows. Try and you'll know.

**Comment by dotmartti** [comment]
Ran also into this and I can confirm it doesn't work on Windows. 
But I could restore cookbooks with Linux for sure. 
Also the directory permissions tip was very helpful - ran into this also when first trying on Linux!

**Comment by pmoosh** [comment]
Latest version will fail with the follow error, when the backup directory is not writable:
Errno::EACCES: Permission denied @ dir_s_mkdir - /tmp/test/tmp

@xmik @dotmartti @ruicovelo

**Comment by fletchowns** [comment]
The error I ran into on Windows with version 0.0.11 was:
```
=== Restoring cookbooks ===
ERROR: Errno::ENOENT: No such file or directory @ unlink_internal
```

@pmoosh maybe we could add a line to the README saying Windows is not supported? Or may throw an error when attempting to do a ```gem install``` on windows to indicate the platform is not supported?

**Comment by pmoosh** [comment]
@fletchowns @dotmartti @ruicovelo I added a simple although not very efficient fix for Windows. Instead of linking to a dir I copy it. Tested cookbook restore with Win 2008R2 and it works 

If you have some time can you try it as well?
clone the repo.
And use bundle install/exec.
Will release the gem later
thanks

pmoosh

**Comment by fletchowns** [comment]
Thanks @pmoosh !

I just had a chance to try out the changes, seems to be *mostly* working for me, not sure if the issues I'm having are pilot error or what.

I've got a local Chef Server VM running to test the backup restore. I ran:
```
knife backup restore -D ./chef_server_backup_2015-09-23_041108 --config ~/.chef/knife_local.rb
```
It went through clients, nodes, roles, data bags, and environments no problem. Then it made it through a couple dozen cookbooks without issue until it suddenly died with:

```
Restoring cookbook ["apt"]
Uploading apt            [2.7.0]
ERROR: SSL Validation failure connecting to host: local.mycorp.com - SSL_read: cert already in hash table
ERROR: Could not establish a secure connection to the server.
Use `knife ssl check` to troubleshoot your SSL configuration.
If your Chef Server uses a self-signed certificate, you can use
`knife ssl fetch` to make knife trust the server's certificates.

Original Exception: OpenSSL::SSL::SSLError: SSL_read: cert already in hash table
```

So then I ran the suggested:
```
$ knife ssl check --config ~/.chef/knife_local.rb
Connecting to host local.mycorp.com:443
Successfully verified certificates from `local.mycorp.com'
```

Then I ran the same ```knife backup restore``` command but it eventually died with:
```
Copy cookbook c:/my-chef-repo/cookbooks/mycorp-chef-server/chef_server_backup_2015-09-23_041108/cookbooks/database-4.0.9 to ./chef_server_backup_2015-09-23_041108/tmp/database
Restoring cookbook ["database"]
Uploading database       [4.0.9]
ERROR: SSL Validation failure connecting to host: local.mycorp.com - SSL_read: cert already in hash table
ERROR: Could not establish a secure connection to the server.
Use `knife ssl check` to troubleshoot your SSL configuration.
If your Chef Server uses a self-signed certificate, you can use
`knife ssl fetch` to make knife trust the server's certificates.
```

Hmm that's weird, already ran the ```knife ssl check```. Oh well I'll just run ```knife backup restore``` again and see what happens:
```
Restoring cookbook ["database"]
Uploading database       [4.0.9]
Uploaded 1 cookbook.
ERROR: Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - ./chef_server_backup_2015-09-23_041108/tmp/database/templates/default
```

So then I tried to clear out that tmp directory:
```
rm -rf ./chef_server_backup_2015-09-23_041108/tmp/
```

Then re-ran the ```knife backup restore``` and it made it past the database cookbook, but then failed at:
```
ERROR: Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - ./chef_server_backup_2015-09-23_041108/tmp/git/attributes
```

I'm thinking the SSL error probably doesn't have anything to do with knife-backup, but maybe something can be done to avoid the dir_s_rmdir error.

**Comment by pmoosh** [comment]
@fletchowns Will look into. What Windows Version are you running?

**Comment by fletchowns** [comment]
@pmoosh this is with Windows 7 and chefdk 0.6.0. I'm upgrading to latest chefdk now to see if behavior is any different.

**Comment by pmoosh** [comment]
@fletchowns I used Windows 2008R2 and chefdk 0.7.0

**Comment by fletchowns** [comment]
@pmoosh still no go with chefdk 0.8.0. I ended up setting ssl_verify_mode to :verify_none to get around those errors for now, but I'm still hitting this on almost every attempt of ```knife backup restore```:
```
ERROR: Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - ./chef_server_backup_2015-09-23_041108/tmp/cron/libraries
```

Seems to be a different cookbook name every time

**Comment by pmoosh** [comment]
I will check on that later. I did actually test with the same settings for SSL you used in the end.

**Comment by pmoosh** [comment]
@fletchowns wasn't really able to reproduce the issue. Made some assumptions and maybe with more output we can close down on this. If you can please try one more time. 

Also tested with 2012R2....

**Comment by fletchowns** [comment]
Thanks @pmoosh !

I'm no longer hitting the ```Directory not empty @ dir_s_rmdir``` error with d5f82c6.

Can't seem to get around the ```cert already in hash table``` error though, even with ```ssl_verify mode :verify_none```. Not sure if that is caused by knife-backup though, I'm gonna hit up the chef IRC channel and see if they have any suggestions.

```
Uploading nginx          [2.7.6]
ERROR: SSL Validation failure connecting to host: chef.mycorp.com - SSL_read: cert already in hash table
ERROR: SSL Validation failure connecting to host: chef.mycorp.com - SSL_read: cert already in hash table
remove dir c:/my-chef-repo/cookbooks/mycorp-chef-server/chef_server_backup_2015-09-23_041108/tmp/nginx-2.7.6
ERROR: Could not establish a secure connection to the server.
Use `knife ssl check` to troubleshoot your SSL configuration.
If your Chef Server uses a self-signed certificate, you can use
`knife ssl fetch` to make knife trust the server's certificates.

Original Exception: OpenSSL::SSL::SSLError: SSL_read: cert already in hash table
```

**Comment by pmoosh** [comment]
@fletchowns - Yeah that doesn't look like it's me :-)
thanks for you support.

**Comment by fletchowns** [comment]
Looks like it might be a bug in ruby core? https://bugs.ruby-lang.org/issues/11033

**Comment by fletchowns** [comment]
Is there any way to control ```--concurrency``` in knife-backup like in [knife upload](https://docs.chef.io/knife_upload.html)? (Assuming knife-backup even uses concurrent connections...)

**Comment by pmoosh** [comment]
@fletchowns - not really.

**Comment by pmoosh** [comment]
@fletchowns I encountered a similar issue just now with knife-ed-backup. Not the exact same error, though:
Original Exception: OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A.
By any chance did you use S3 for cookbook storage?

**Comment by fletchowns** [comment]
@pmoosh I'm using S3 for cookbook backups. I run `knife backup`, `tar xvzf` the output, and then `aws s3 cp` it to S3.

For restoring backup, it's basically just the reverse of those 3 commands.

**Comment by pmoosh** [comment]
@fletchowns My question was misleading. But from your reply I assume your chef server uses local filesystem for cook storage and S3(bookshelf).

thanks

**Comment by xmik** [comment]
Thanks @pmoosh for taking care of this issue and this repository.
