### ISSUE TITLE
Chefserver 12: problem backing up/restoring users

### ISSUE THREAD

**Issue by Marjorie-Cecile** [mdxp/knife-backup#43]
when I export a user I get a file like this:
{
"name":"",
"public_key":"-----BEGIN PUBLIC KEY-----\nxxx\n-----END PUBLIC KEY-----\n\n",
"admin":false
}
the value for the name is always empty and it looks like ChefServer12 uses username instead of name which also prevents the restore.

**Comment by pmoosh** [comment]
Upon further review I think tis issue is related to this [chef-server issue](https://github.com/chef/chef/pull/3438)

**Comment by pmoosh** [comment]
@Marjorie-Cecile: I looked into this issue more thoroughly and came to the conclusion that migrating users from Open Source Chef 11 to Chef 12 is not possible. On the topic of backup and restore in a Chef Server 12, we need to look into this a bit more. One of the obstacles is that you need to be pivotal user.

For now there is no support for users for Chef Server 12.

**Comment by pmoosh** [comment]
@Marjorie-Cecile: we are not supporting users going forward. Thank you for bringing this issue to our attention.

See changes in #46
