### ISSUE TITLE
Chef 12 incompatibilities (ACLs, users)

### ISSUE THREAD

**Issue by chewi** [mdxp/knife-backup#47]
Please fix this for Chef 12 or slap a big warning across it. First, it failed to recreate the users. This was fine for me as I only had 2 anyway. What I didn't realise until later was that it also didn't migrate the ACLs, which are a new thing in 12, so I run into chef/chef-server#63.

**Comment by pmoosh** [comment]
@chewi - Not sure which version of the plugin you use:
IN the README it states:
- users (chef 11 - Open Source)

We also have warnings that state:
ui.warn "users export only supported on chef == 11"
ui.warn "users restore only supported on chef == 11".

It is correct that we don't do handle ACL. They are not even an option.

Have you looked at:
https://github.com/chef/knife-ec-backup

thanks

**Comment by chewi** [comment]
I used the latest release, 0.0.11, which does not include those messages.

The recent activity had led me to think that the README had simply not been updated. If it doesn't work with 12, I would expect it to say explicitly say so.

I was not aware of knife-ec-backup but I managed to fix the ACLs so all is good now. I just wanted to prevent other people from falling into the trap.

**Comment by pmoosh** [comment]
It does work with Chef Server 12, but It will not backup or restore everything and it is limited to a single organization. If you need more have a look at knife-ec-backup. This will backup and restore a complete Chef Server 12.
