### ISSUE TITLE
Restore cookbooks fails all if a single cookbook has syntax errors

### ISSUE THREAD

**Issue by devryan** [mdxp/knife-backup#50]
When restoring over a hundred cookbooks+versions, if a single cookbook has syntax errors, the whole process bails out.  This is pretty frustrating.  It should skip if error and continue on with the rest, and just warn.

**Comment by devryan** [comment]
PS, thanks for all your work on this plugin, thing works awesome aside from this issue, and it's helping with testing a Chef 11-12 upgrade since I can easily backup+restore using this plugin :)

**Comment by pmoosh** [comment]
Closing with #52
