### ISSUE TITLE
-I option doesn't work

### ISSUE THREAD

**Issue by mingleiwang** [mdxp/knife-backup#54]
Not sure how to use -I option(--ignore-metadata-errors), I tried several ways, they all don't work. What's the correct format to use -I option?

**Comment by pmoosh** [comment]
@mingleiwang  Can you give more details and show me the output? Also what version do you use?
The --ignore-metadata-errors is new to the 0.0.12 version.

**Comment by mingleiwang** [comment]
Actually I used the wrong version. Thanks for your help.
