### ISSUE TITLE
restore of an existing client "fails"

### ISSUE THREAD

**Issue by nvwls** [mdxp/knife-backup#8]
When doing a restore, nodes are overridden.  clients are not.  It warns that the client already exists but does not restore the previous data.

Say, a client is recreated but I want to revert to the backup.  Sure, I can delete the client and then restore but it would easier if the restore deleted it and then recreated it.  Or do an api.put() if the api.post() fails

**Comment by pmoosh** [comment]
This is a known limitation documented in the Readme: currently it is not possible to overwritte a client object already available on the target server and these will be skipped.

thanks @nvwls
